function G = barabasi_albert(n,k,option)

%BARABASI_ALBERT Returns a graph generated by the
%   model of Barabasi & Albert. It follows a power-law
%   degree distribution: P(i) = i^(-3).
%
%   G = BARABASI_ALBERT(n) returns a graph of n
%   nodes following the Barabasi & Albert model.
%
%   G = BARABASI_ALBERT(n,k) returns a graph of n
%   nodes following the Barabasi & Albert model with
%   a factor k regulating the sparsity of the graph
%   such that P(i) = d(i)/sum(d(i))*k.
%
%   G = BARABASI_ALBERT(...,'sparse') returns the
%   above, but in sparse matrix format.
%
%   Copyright (c) 2013, Fredrik Johansson 
%   frejohk@chalmers.se


if(nargin<2)
  k = 1;
end
if(nargin<3)
    option = '';
end

if(strcmp(option,'sparse'))
    G = sparse([]);
else
    G = zeros(n,n);
end

G(1,2) = 1;
G(2,1) = 1;

d = zeros(n,1);
d(1) = 1;
d(2) = 1;
D = 2;

for i=3:n 
    if(n>10000 && mod(i,1000)==0)
        disp(i)
    end
    I = 1:i-1;    
    p = d(I)/D;
    r = rand(length(I),1);
    J = find(r<p*k);
    G(i,J) = 1;
    G(J,i) = 1;
    d(J) = d(J) + 1;
    d(i) = d(i) + length(J);
    D = D + 2*length(J);
    
%     for j=1:i-1
%         p = d(j)/D;
%         r = rand;
%         if(r<p*k)
%             G(i,j) = 1;
%             G(j,i) = 1;
%             d(j) = d(j) + 1;
%             d(i) = d(i) + 1;
%             D = D + 2;
%         end
%     end
end