experiment_setup;

dataset = 'GENP';

paramsFilename = ...
    ['./my_code/data/params_', dataset];
load(paramsFilename);



%sizes = [100, 200, 500, 1000, 2000, 5000, 10000, 20000];
%nSizes = length(sizes);


runtimesFilename = ['./my_code/data/runtimes_', dataset];
load(runtimesFilename)
% loads stdPrepRuntimes, stdQueryRuntimes, smpFstPrepRuntimes, 
% smpFstQueryRuntimes, smpLstPrepRuntimes, smpLstQueryRuntimes

errAccFilename = ['./my_code/data/errAcc_', dataset];
load(errAccFilename);
% loads stdAccuracy, cat([smpLst smpFst vor] [Errors Accuracies])

%%

toPlotInds = 1;

stdPrepRuntimes = stdPrepRuntimes(:, toPlotInds);
stdQueryRuntimes = stdQueryRuntimes(:, toPlotInds);
smpFstPrepRuntimes = smpFstPrepRuntimes(:, toPlotInds);
smpFstQueryRuntimes = smpFstQueryRuntimes(:, toPlotInds);
smpLstPrepRuntimes = smpLstPrepRuntimes(:, toPlotInds);
smpLstQueryRuntimes = smpLstQueryRuntimes(:, toPlotInds);
vorPrepRuntimes = vorPrepRuntimes(:, toPlotInds, :);
vorQueryRuntimes = vorQueryRuntimes(:, toPlotInds, :);

stdAccuracy = stdAccuracy(:, toPlotInds);
smpLstErrors = smpLstErrors(:, toPlotInds);
smpFstErrors = smpFstErrors(:, toPlotInds);
vorErrors = vorErrors(:, toPlotInds, :);
smpLstAccuracies = smpLstAccuracies(:, toPlotInds);
smpFstAccuracies = smpFstAccuracies(:, toPlotInds);
vorAccuracies = vorAccuracies(:, toPlotInds, :);

sizesToPlot = sizes(toPlotInds);

stdTotalRuntimes = stdPrepRuntimes+stdQueryRuntimes;
smpFstTotalRuntimes = smpFstPrepRuntimes+smpFstQueryRuntimes;
smpLstTotalRuntimes = smpLstPrepRuntimes+smpLstQueryRuntimes;
vorTotalRuntimes = vorPrepRuntimes+vorQueryRuntimes;


%% Show results
% 

figure(1)
semilogy(sizesToPlot, stdQueryRuntimes, '-x', ...
    sizesToPlot, smpLstQueryRuntimes(1, :), '-x', ...
    sizesToPlot, smpLstQueryRuntimes(end, :), '-x', ...
    sizesToPlot, smpFstQueryRuntimes(1, :), '-x', ...
    sizesToPlot, smpFstQueryRuntimes(end, :), '-x', ...
    sizesToPlot, vorQueryRuntimes(3, :, 1), '-x', ...
    sizesToPlot, vorQueryRuntimes(3, :, 2), '-x')
legend('Standard', ['SampleLast (m=', num2str(ms(1)), ')'], ...
    ['SampleLast (m=', num2str(ms(end)), ')'], ...
    ['SampleFirst (m=', num2str(ms(1)), ')'], ...
    ['SampleFirst (m=', num2str(ms(end)), ')'], ...
    ['Voronoi (m=', num2str(ms(3)), ', p=', ...
    num2str(densities(1)), ')'], ...
    ['Voronoi (m=', num2str(ms(3)), ', p=', ...
    num2str(densities(2)), ')'], ...
    'Location', 'NorthEastOutside')
title(['Kernel computation query runtime on ', dataset, ...
    'X w/ size(x) in [', num2str(sizesToPlot(1)), ', ', ...
    num2str(sizesToPlot(end)), ']'])
xlabel('Graph size')
ylabel('Mean query runtime (over 20 trials)')

%%

figure(2)
semilogy(sizesToPlot, stdTotalRuntimes, '-x', ...
    sizesToPlot, smpLstTotalRuntimes(1, :), '-x', ...
    sizesToPlot, smpLstTotalRuntimes(end, :), '-x', ...
    sizesToPlot, smpFstTotalRuntimes(1, :), '-x', ...
    sizesToPlot, smpFstTotalRuntimes(end, :), '-x', ...
    sizesToPlot, vorTotalRuntimes(1, :, 1), '-x', ...
    sizesToPlot, vorTotalRuntimes(1, :, 2), '-x')
legend('Standard', ['SampleLast (m=', num2str(ms(1)), ')'], ...
    ['SampleLast (m=', num2str(ms(end)), ')'], ...
    ['SampleFirst (m=', num2str(ms(1)), ')'], ...
    ['SampleFirst (m=', num2str(ms(end)), ')'], ...
    ['Voronoi (m=', num2str(ms(1)), ', p=', ...
    num2str(densities(1)), ')'], ...
    ['Voronoi (m=', num2str(ms(1)), ', p=', ...
    num2str(densities(2)), ')'], ...
    'Location', 'NorthWest')
    %'Standard', 'Standard w/ preprocessing', ...
title(['Total kernel computation runtime on ', dataset, 'X (X in [', ...
    num2str(sizesToPlot(1)), ', ', num2str(sizesToPlot(end)), '])'])
xlabel('Graph size')
ylabel('Mean runtime (over 20 trials)')

%%

graphSizeInd = 1;
graphSize = sizes(graphSizeInd);

figure(3)
semilogy([0 ms(end)+100], [1 1]*(stdQueryRuntimes(graphSizeInd)), ...
    [0 ms(end)+100], [1 1]*(stdTotalRuntimes(graphSizeInd)), 'k', ...
    ms, smpLstQueryRuntimes(:, graphSizeInd), '--o', ...
    ms, smpLstTotalRuntimes(:, graphSizeInd), '--o', ...
    ms, smpFstTotalRuntimes(:, graphSizeInd), '--o', ...
    ms, vorTotalRuntimes(:, graphSizeInd, 1), '--o', ...
    ms, vorTotalRuntimes(:, graphSizeInd, end), '--o')
xlim([0 ms(end)*1.1])
legend('Standard, query', 'Standard, total', ...
    'SampleLast, query', 'SampleLast, total', ...
    'SampleFirst, total', ...
    ['Voronoi (p=', num2str(densities(1)) ,', total'], ...
    ['Voronoi (p=', num2str(densities(end)) ,', total'], ...    
    'Location', 'NorthEastOutside')
title(['Kernel computation runtime on ', dataset, num2str(graphSize)])
xlabel('No. of samples')
ylabel('Mean runtime (per query or in total)')

%% Error, by graph size:

figure(4)
%plot(sizesToPlot, sizesToPlot*0, '-x', ...
%    sizesToPlot, smpLstErrors(1, :), '-x', ...
plot(sizesToPlot, smpLstErrors(1, :), '-x', ...
    sizesToPlot, smpLstErrors(end, :), '-x', ...
    sizesToPlot, smpFstErrors(1, :), '-x', ...
    sizesToPlot, smpFstErrors(end, :), '-x', ...
    sizesToPlot, vorErrors(1, :, 1), '-x', ...
    sizesToPlot, vorErrors(end, :, 1), '-x')

%xlim([0 ms(end)*1.1])

%legend('Standard', ...
%    ['SampleLast, m=', num2str(ms(1))], ...
legend(['SampleLast, m=', num2str(ms(1))], ...
    ['SampleLast, m=', num2str(ms(end))], ...
    ['SampleFirst, m=', num2str(ms(1))], ...
    ['SampleFirst, m=', num2str(ms(end))], ...
    ['Voronoi, m=', num2str(ms(1)), ', p=', num2str(densities(1))], ...
    ['Voronoi, m=', num2str(ms(end)), ', p=', num2str(densities(1))], ...
    'Location', 'NorthEastOutside')

title(['Kernel value errors on ', dataset, 'X (X in [', ...
    num2str(sizesToPlot(1)), ', ', ...
    num2str(sizesToPlot(end)), '])'])
xlabel('Graph size')
ylabel('Mean kernel value error (over 20 trials)')

%% Error, by sample size:

graphSizeInd = 1;
graphSize = sizes(graphSizeInd);

figure(5)
plot([0 ms(end)+100], [0 0], ...
    ms, smpLstErrors(:, graphSizeInd), '--o', ...
    ms, smpFstErrors(:, graphSizeInd), '--o', ...
    ms, vorErrors(:, graphSizeInd, 1), '--o', ...
    ms, vorErrors(:, graphSizeInd, end), '--o')
xlim([0 ms(end)*1.1])
legend('Standard', ...
    'SampleLast', 'SampleFirst', ...
    ['Voronoi, p=', num2str(densities(1))], ...
    ['Voronoi, p=', num2str(densities(end))], ...
    'Location', 'NorthEastOutside')
title(['Kernel value errors on ', dataset, num2str(graphSize)])
xlabel('Sample size')
ylabel('Mean kernel value error (over 20 trials)')

%% Accuracy, by graph size:

figure(6)
plot(sizesToPlot, stdAccuracy, '-x', ...
    sizesToPlot, smpLstAccuracies(1, :), '-x', ...
    sizesToPlot, smpLstAccuracies(end, :), '-x', ...
    sizesToPlot, smpFstAccuracies(1, :), '-x', ...
    sizesToPlot, smpFstAccuracies(end, :), '-x', ...
    sizesToPlot, vorAccuracies(1, :, 1), '-x', ...
    sizesToPlot, vorAccuracies(end, :, 1), '-x')
%xlim([0 ms(end)*1.1])

legend('Standard', ...
    ['SampleLast, m=', num2str(ms(1))], ...
    ['SampleLast, m=', num2str(ms(end))], ...
    ['SampleFirst, m=', num2str(ms(1))], ...
    ['SampleFirst, m=', num2str(ms(end))], ...
    ['Voronoi, m=', num2str(ms(1)), ', p=', num2str(densities(1))], ...
    ['Voronoi, m=', num2str(ms(end)), ', p=', num2str(densities(1))], ...
    'Location', 'NorthEastOutside')

title(['Kernel accuracies on ', dataset, 'X (X in [', ...
    num2str(sizesToPlot(1)), ', ', ...
    num2str(sizesToPlot(end)), '])'])
xlabel('Graph size')
ylabel('Mean kernel accuracy in % (over 20 trials)')

%% Accuracy, by sample size:

graphSizeInd = 1;
graphSize = sizes(graphSizeInd);

figure(7)
plot([0 ms(end)+100], stdAccuracy(graphSizeInd)*[1 1], ...
    ms, smpLstAccuracies(:, graphSizeInd), '--o', ...
    ms, smpFstAccuracies(:, graphSizeInd), '--o', ...
    ms, vorAccuracies(:, graphSizeInd, 1), '--o', ...
    ms, vorAccuracies(:, graphSizeInd, 2), '--o')
xlim([0 ms(end)*1.1])
legend('Standard', ...
    'SampleLast', 'SampleFirst', ...
    ['Voronoi, p=', num2str(densities(1))], ...
    ['Voronoi, p=', num2str(densities(2))], ...
    'Location', 'NorthEastOutside')
title(['Kernel accuracies on ', dataset, num2str(graphSize)])
xlabel('Sample size')
ylabel('Mean kernel accuracy in % (over 20 trials)')

