experiment_setup;

dataset = 'GENP';
datasetName = 'ER';

paramsFilename = ...
    ['./my_code/data/params_', dataset];
load(paramsFilename);



%sizes = [100, 200, 500, 1000, 2000, 5000, 10000, 20000];
%nSizes = length(sizes);


runtimesFilename = ['./my_code/data/runtimes_', dataset];
load(runtimesFilename)
% loads stdPrepRuntimes, stdQueryRuntimes, smpFstPrepRuntimes, 
% smpFstQueryRuntimes, smpLstPrepRuntimes, smpLstQueryRuntimes

errAccFilename = ['./my_code/data/errAcc_', dataset];
load(errAccFilename);
% loads stdAccuracy, cat([smpLst smpFst vor] [Errors Accuracies])



%%

toPlotInds = 1:5;

stdPrepRuntimes = stdPrepRuntimes(:, toPlotInds);
stdQueryRuntimes = stdQueryRuntimes(:, toPlotInds);

smpFstPrepRuntimes = smpFstPrepRuntimes(:, toPlotInds);
smpFstQueryRuntimes = smpFstQueryRuntimes(:, toPlotInds);

smpFstPrepOps= smpFstPrepOps(:, toPlotInds);
smpFstQueryOps= smpFstQueryOps(:, toPlotInds);

smpLstPrepRuntimes = smpLstPrepRuntimes(:, toPlotInds);
smpLstQueryRuntimes = smpLstQueryRuntimes(:, toPlotInds);

stdAccuracy = stdAccuracy(:, toPlotInds);

smpLstErrors = smpLstErrors(:, toPlotInds);
smpLstDistErrors = smpLstDistErrors(:, toPlotInds);

smpFstErrors = smpFstErrors(:, toPlotInds);
smpFstDistErrors = smpFstDistErrors(:, toPlotInds);

smpLstAccuracies = smpLstAccuracies(:, toPlotInds);
smpFstAccuracies = smpFstAccuracies(:, toPlotInds);

sizesToPlot = sizes(toPlotInds);

stdTotalRuntimes = stdPrepRuntimes+stdQueryRuntimes;

smpFstTotalRuntimes = smpFstPrepRuntimes+smpFstQueryRuntimes;
smpFstTotalOps = smpFstPrepOps+smpFstQueryOps;

smpLstTotalRuntimes = smpLstPrepRuntimes+smpLstQueryRuntimes;

%% Show results
% 

figure(1)
loglog(sizesToPlot, stdQueryRuntimes, '-x', ...
    sizesToPlot, smpLstQueryRuntimes(1, :), '-x', ...
    sizesToPlot, smpLstQueryRuntimes(end, :), '-x', ...
    sizesToPlot, smpFstQueryRuntimes(1, :), '-x', ...
    sizesToPlot, smpFstQueryRuntimes(end, :), '-x')
legend('Standard', ['SampleLast (m=', num2str(ms(1)), ')'], ...
    ['SampleLast (m=', num2str(ms(end)), ')'], ...
    ['SampleFirst (m=', num2str(ms(1)), ')'], ...
    ['SampleFirst (m=', num2str(ms(end)), ')'], ...
    'Location', 'NorthEastOutside')
title(['Kernel computation query runtime on ', datasetName, ...
    'X w/ size(x) in [', num2str(sizesToPlot(1)), ', ', ...
    num2str(sizesToPlot(end)), ']'])
xlabel('Graph size')
ylabel(['Mean query runtime (over ', num2str(nTrials), ' trials)'])

%%

figure(2)
loglog(sizesToPlot, stdTotalRuntimes, '-x', ...
    sizesToPlot, smpLstTotalRuntimes(1, :), '-x', ...
    sizesToPlot, smpLstTotalRuntimes(end, :), '-x', ...
    sizesToPlot, smpFstTotalRuntimes(1, :), '-x', ...
    sizesToPlot, smpFstTotalRuntimes(end, :), '-x')
legend('Standard', ...
    ['SampleLast (m=', num2str(ms(1)), ')'], ...
    ['SampleLast (m=', num2str(ms(end)), ')'], ...
    ['SampleFirst (m=', num2str(ms(1)), ')'], ...
    ['SampleFirst (m=', num2str(ms(end)), ')'], ...
    'Location', 'NorthEastOutside')
    %'Standard', 'Standard w/ preprocessing', ...
title(['Total kernel computation runtime on ', datasetName, 'X (X in [', ...
    num2str(sizesToPlot(1)), ', ', num2str(sizesToPlot(end)), '])'])
xlabel('Graph size')
ylabel(['Mean runtime (over ', num2str(nTrials), ' trials)'])

%%

graphSizeInd = 5;
graphSize = sizes(graphSizeInd);

figure(3)
semilogy([0 ms(end)+100], [1 1]*(stdQueryRuntimes(graphSizeInd)), ...
    [0 ms(end)+100], [1 1]*(stdTotalRuntimes(graphSizeInd)), 'k', ...
    ms, smpLstQueryRuntimes(:, graphSizeInd), '--o', ...
    ms, smpLstTotalRuntimes(:, graphSizeInd), '--o', ...
    ms, smpFstTotalRuntimes(:, graphSizeInd), '--o')
xlim([0 ms(end)*1.1])
legend('Standard, query', 'Standard, total', ...
    'SampleLast, query', 'SampleLast, total', ...
    'SampleFirst, total', ...
    'Location', 'NorthEastOutside')
title(['Kernel computation runtime on ', datasetName, num2str(graphSize)])
xlabel('No. of samples')
ylabel('Mean runtime (per query or in total)')

%% Error and acc, by graph size:

m1 = 2;
m2 = 4;
m3 = nMValues;


figure(4)
clf
plot1 = plot(sizesToPlot, smpLstErrors(m1, :), '-x', ...
    sizesToPlot, smpLstErrors(m2, :), '-x', ...
    sizesToPlot, smpLstErrors(m3, :), '-x', ...
    sizesToPlot, smpFstErrors(m1, :), '-x', ...
    sizesToPlot, smpFstErrors(m2, :), '-x', ...
    sizesToPlot, smpFstErrors(m3, :), '-x', ...
    sizesToPlot, sizesToPlot.*0);

title(['Kernel accuracies on ', datasetName, 'X (X in [', ...
    num2str(sizesToPlot(1)), ', ', ...
    num2str(sizesToPlot(end)), '])']);
xlabel('Graph size')
ylabel(['Mean kernel error (over ', num2str(nTrials), ' trials)'])

legend(['SampleLast, m=', num2str(ms(m1))], ...
    ['SampleLast, m=', num2str(ms(m2))], ...
    ['SampleLast, m=', num2str(ms(m3))], ...
    ['SampleFirst, m=', num2str(ms(m1))], ...
    ['SampleFirst, m=', num2str(ms(m2))], ...
    ['SampleFirst, m=', num2str(ms(m3))], ...
    'Location', 'SouthOutside');

figure(5)
clf
plot2 = plot(sizesToPlot, smpLstAccuracies(m1, :), '-x', ...
    sizesToPlot, smpLstAccuracies(m2, :), '-x', ...
    sizesToPlot, smpLstAccuracies(m3, :), '-x', ...
    sizesToPlot, smpFstAccuracies(m1, :), '-x', ...
    sizesToPlot, smpFstAccuracies(m2, :), '-x', ...
    sizesToPlot, smpFstAccuracies(m3, :), '-x', ...
    sizesToPlot, stdAccuracy, '-x');
%xlim([0 ms(end)*1.1])

xlabel('Graph size')
ylabel(['Mean kernel accuracy in % (over ', num2str(nTrials), ' trials)'])

title(['Kernel accuracies on ', datasetName, 'X (X in [', ...
    num2str(sizesToPlot(1)), ', ', ...
    num2str(sizesToPlot(end)), '])']);

legend(['SampleLast, m=', num2str(ms(m1))], ...
    ['SampleLast, m=', num2str(ms(m2))], ...
    ['SampleLast, m=', num2str(ms(m3))], ...
    ['SampleFirst, m=', num2str(ms(m1))], ...
    ['SampleFirst, m=', num2str(ms(m2))], ...
    ['SampleFirst, m=', num2str(ms(m3))], ...
    'Location', 'SouthOutside');
% legend(['SampleLast, m=', num2str(ms(m1))], ...
%     ['SampleLast, m=', num2str(ms(m2))], ...
%     ['SampleLast, m=', num2str(ms(m3))], ...
%     ['SampleFirst, m=', num2str(ms(m1))], ...
%     ['SampleFirst, m=', num2str(ms(m2))], ...
%     ['SampleFirst, m=', num2str(ms(m3))], ...
%     'Location', 'NorthEastOutside')



%% Error, by sample size:

graphSizeInd = 3;
graphSize = sizes(graphSizeInd);

figure(5)
plot([0 ms(end)+100], [0 0], ...
    ms, smpLstErrors(:, graphSizeInd), '--o', ...
    ms, smpFstErrors(:, graphSizeInd), '--x')
xlim([0 ms(end)*1.1])
legend('Standard', ...
    'SampleLast', 'SampleFirst', ...
    'Location', 'NorthEastOutside')
title(['Kernel value errors on ', datasetName, num2str(graphSize)])
xlabel('Sample size')
ylabel(['Mean kernel value error (over ', num2str(nTrials), ' trials)'])

%% Distribution error, by sample size:

graphSizeInd = 3;
graphSize = sizes(graphSizeInd);

figure(6)
plot([0 ms(end)+100], [0 0], ...
    ms, smpLstDistErrors(:, graphSizeInd), '--o', ...
    ms, smpFstDistErrors(:, graphSizeInd), '--o')
xlim([0 ms(end)*1.1])
legend('Standard', ...
    'SampleLast', 'SampleFirst', ...
    'Location', 'NorthEastOutside')
title(['Shortest path distribution errors on ', datasetName, num2str(graphSize)])
xlabel('Sample size')
ylabel(['Mean sp-distribution error (over ', num2str(nTrials), ' trials)'])

%% Accuracy, by graph size:

m1 = 1;
m2 = nMValues;

figure(7)
plot(sizesToPlot, stdAccuracy, '-x', ...
    sizesToPlot, smpLstAccuracies(m1, :), '-x', ...
    sizesToPlot, smpLstAccuracies(m2, :), '-x', ...
    sizesToPlot, smpFstAccuracies(m1, :), '-x', ...
    sizesToPlot, smpFstAccuracies(m2, :), '-x')
%xlim([0 ms(end)*1.1])

legend('Standard', ...
    ['SampleLast, m=', num2str(ms(m1))], ...
    ['SampleLast, m=', num2str(ms(m2))], ...
    ['SampleFirst, m=', num2str(ms(m1))], ...
    ['SampleFirst, m=', num2str(ms(m2))], ...
    'Location', 'NorthEastOutside')

title(['Kernel accuracies on ', datasetName, 'X (X in [', ...
    num2str(sizesToPlot(1)), ', ', ...
    num2str(sizesToPlot(end)), '])'])
xlabel('Graph size')
ylabel(['Mean kernel accuracy in % (over ', num2str(nTrials), ' trials)'])

%% Accuracy, by sample size:

graphSizeInd = 4;
graphSize = sizes(graphSizeInd);

figure(8)
plot([0 ms(end)+100], stdAccuracy(graphSizeInd)*[1 1], ...
    ms, smpLstAccuracies(:, graphSizeInd), '--o', ...
    ms, smpFstAccuracies(:, graphSizeInd), '--o')
xlim([0 ms(end)*1.1])
legend('Standard', ...
    'SampleLast', 'SampleFirst', ...
    'Location', 'NorthEastOutside')
title(['Kernel accuracies on ', datasetName, num2str(graphSize)])
xlabel('Sample size')
ylabel(['Mean kernel accuracy in % (over ', num2str(nTrials), ' trials)'])


%%

flog = @(x)x.*log(x);
a = 10000;
b = 5*10^6;

figure(9)
loglog(sizesToPlot, smpFstTotalOps(1, :), '-x', ...
         sizesToPlot, smpFstTotalOps(end, :), '-x')%, ...
%         sizesToPlot, b+a*flog(sizesToPlot), '-.')
legend(['SampleFirst, total (m=', num2str(ms(1)), ')'], ...
       ['SampleFirst, total (m=', num2str(ms(end)), ')'], ... % 'N log N', ...
       'Location', 'NorthWest')
title(['Dijkstra operations counts for ', datasetName, 'X (X in [', ...
    num2str(sizesToPlot(1)), ', ', num2str(sizesToPlot(end)), '])'])
xlabel('Graph size')
ylabel(['Mean operations count (over ', num2str(nTrials), ' trials)'])

